package Arul1;
public class Java {
    public static void main(String[] args) {
//        mengubah string jadi tipe data primitif
        String a = "13000";
        int harga = Integer.parseInt(a);
        System.out.println("Harga ayam geprek :" + harga);
        
        String c = "100000";
        long Rp = Long.parseLong(c);
        System.out.println("uang terbesar indonesia yaitu Rp"+Rp);
    }
}
