
package Arul;

import java.util.Scanner;

public class Java9 {
    public static void main(String[] args) {
        Scanner in = new Scanner(System.in);
        System.out.print("masukkan nama asli : ");
        String nama = in.nextLine();
        System.out.println("Hallo nama panggilan saya adalah " + nama);
//        masukkan nama asli : arul
//        Hallo nama panggilan saya adalah arul
    }
 
}
