
package Arul1;

import java.util.Scanner;

public class Java {
    public static void main(String[] args) {
 //day28 operator perbandingan
        int a = in.nextInt();
        int b = in.nextInt();
        System.out.println("apakah nilai a dan b sama  "+(a==b));
       
        int c = in.nextInt();
        int d = in.nextInt();
        System.out.println("apakah nilai a dan b sama  "+(c!=d));
        
        /* operator perbandingan (==) ini berkaitan dengan bolean 
        saat kita memasukkan nilai yang sama di output maka hasil
        yang akan keluar adalah true sedangkan kalau nilai nya 
        berbeda akan false.
        
        operator perbandingan (!=) ini berkebalikan dengan ==
        karna cara kerja != adalah jika kita memasukkan nilai 
        yang berbeda maka hasil yang di tunjukkan itu true
        sedangkan jika kita input nilai yang sama maka akan 
        false .
        itulah perbedaan yang saya liat dari keduanya
        */
       
}
}
