package latihan;

import java.util.Scanner;

public class elseIf {
    public static void main(String[] args) {
        Scanner in = new Scanner(System.in);
         // day 25 incremend dan decremend
        System.out.println("masukkan angka :");
        int angka1 = in.nextInt();
        System.out.println("masukkan angka2 :");
        int angka2 = in.nextInt();
        
        angka1++;
        angka2--;
        
        System.out.println("masukkan angka1 ingkremen " +angka1);
        System.out.println("masukkan angka1 decremen " +angka2);
    }
 
}
