
package latihan;

import java.util.Scanner;

public class elseIf {
    public static void main(String[] args) {
        Scanner in = new Scanner(System.in);
        // luas pesegipanjang 23
        
        System.out.print("masukkan panjang :");
        int p = in.nextInt();
        System.out.print("masukkan lebar :");
        int l = in.nextInt();
        System.out.println("jadi luas persegi panjang adalah " +(p*l));
    }
 
}
