package Arul;
public class Java {
    public static void main(String[] args) {
        System.out.print("Nama saya arul ");
        System.out.println("Saya berasal dari topoyo");
        System.out.printf("saya ALumni dari %s umur saya saat ini %d tahun ","SMAN 1 Topoyo",19 );
        // kodingan day2 saya gunakan untuk day 3 !!
        /*Di sini saya membuat bio data diri saya menggunakan tiga kata perintah yang berbeda 
        pertama saya menggunakan print saja dan yang kedua saya menggunakan Println dan yang
        ketiga saya menggunakan printf */
        // Terima kasih
    }
}

