package Arull;

import java.util.Scanner;

public class Java1 {

    public static void main(String[] args) {
      //day31 logika &&
        System.out.print(" masukkan nilai arul :");
        int a = in.nextInt();
        System.out.print("masukkan nilai muha' :");
        int m = in.nextInt();
        boolean c = a>=27 && m>=27 ;
        boolean d = a<=27 && m<=27;
        System.out.println(c);
        System.out.println(d);
