package Arull;

import java.util.Scanner;

public class Java1 {

    public static void main(String[] args) {
      //day31 logika &&
        System.out.print(" masukkan nilai arul :");
        int a = in.nextInt();
        System.out.print("masukkan nilai muha' :");
        int m = in.nextInt();
        boolean c = a>=m && m>=a ;
        boolean d = a<=m && a>=m;
        System.out.println(c);
        System.out.println(d);
    }
}
