package Arull;

import java.util.Scanner;

public class Java1 {

    public static void main(String[] args) {
        Scanner in = new Scanner(System.in);
  //day 52 perulangan while
        System.out.print("Masukkan angka :");
        int angka = in.nextInt();
        while(angka<=100){
            System.out.println(angka);
            angka+=2;
            
            
        }  
        System.out.println("perulangan berheniti");



       
         
    }
}


