package Arul;
public class Java3 {
    public static void main(String[] args) {
     byte umur = -127;
     short tahun = 2005;
     int tinggi = 173;
     long tanggal = 29102005l;
        System.out.println("isi tipe data byte :" + umur );        
        System.out.println("isi tipe data short :" + tahun);        
        System.out.println("isi tipe data int :" + tinggi);        
        System.out.println("isi tipe data long :" + tanggal);        
    }
}
