
package aruls;

import java.util.Arrays;
import java.util.Scanner;
public class java {
    static Scanner in = new Scanner(System.in);
    public static void main(String[] args) {
       String arr[]={"arul","lupa","commit","mheeeee"};
        System.out.print(arr[0]+",");
        System.out.print(arr[1]+",");
        System.out.print(arr[2]+",");
        System.out.print(arr[3]+"\n");
        

   }
}
