package aruls1;

import java.util.Scanner;


public class voidJava {
    public static void main(String[] args) {
        Scanner in =new Scanner(System.in);
        
        // day 97 : Menghitung Luas Persegi dengan Method Non-void dan parameterny
        int persegi=in.nextInt();
        System.out.println("hasil persegi :"+nana(persegi));
  }
    static int nana(int l){
        return l*l;
    }
}
